// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/container/v1beta1/cluster_service.proto

package com.google.container.v1beta1;

public interface NodeConfigDefaultsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.container.v1beta1.NodeConfigDefaults)
    com.google.protobuf.MessageOrBuilder {
}
